name: Lurchers Rule
favicon: null
layout_spectrum: 0.50935
typography_spectrum: 0.47739
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ba95c0'
    - '#52405a'
    - '#211926'
    - '#f1ccf5'
    - '#b2896b'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
