name: Lurchers Rule
favicon: null
layout_spectrum: 0.5873467377386987
typography_spectrum: 0.8643078203313053
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5552855469286442
  lightness: 0.9829328125342727
  saturation: 0.29800054081715643
  rhythmicContrast: 0.010147056309506297
purpose: []
