name: Lurchers Rule
favicon: null
layout_spectrum: 1
typography_spectrum: 0.8643078203313053
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 1
  lightness: 0.9829328125342727
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
